# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T14:18:40+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field, RootModel, constr


class GetRawMessageContentRequest(BaseModel):
    pass


class InvalidContentLocation(RootModel[Any]):
    root: Any


class MessageFrozen(RootModel[Any]):
    root: Any


class MessageRejected(RootModel[Any]):
    root: Any


class PutRawMessageContentResponse(BaseModel):
    pass


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class MessageContentBlob(RootModel[str]):
    root: str


class MessageIdType(
    RootModel[constr(pattern=r'[a-z0-9\-]*', min_length=1, max_length=120)]
):
    root: constr(pattern=r'[a-z0-9\-]*', min_length=1, max_length=120)


class S3BucketIdType(
    RootModel[constr(pattern=r'^[a-z0-9][a-z0-9\-]*', min_length=3, max_length=63)]
):
    root: constr(pattern=r'^[a-z0-9][a-z0-9\-]*', min_length=3, max_length=63)


class S3KeyIdType(
    RootModel[constr(pattern=r'[a-zA-Z0-9\-/]*', min_length=1, max_length=1024)]
):
    root: constr(pattern=r'[a-zA-Z0-9\-/]*', min_length=1, max_length=1024)


class S3VersionType(RootModel[constr(pattern=r'.+', min_length=1, max_length=1024)]):
    root: constr(pattern=r'.+', min_length=1, max_length=1024)


class GetRawMessageContentResponse(BaseModel):
    messageContent: MessageContentBlob


class S3Reference(BaseModel):
    bucket: S3BucketIdType
    key: S3KeyIdType
    objectVersion: Optional[S3VersionType] = None


class Content(BaseModel):
    s3Reference: Optional[S3Reference] = None


class MessagesMessageIdPostRequest(BaseModel):
    content: Content = Field(
        ...,
        description='<p>Provides the MIME content of the updated email message as an S3 object. All MIME content must meet the following criteria:</p> <ul> <li> <p>Each part of a multipart MIME message must be formatted properly.</p> </li> <li> <p>Attachments must be of a content type that Amazon SES supports. For more information, see <a href="https://docs.aws.amazon.com/ses/latest/DeveloperGuide/mime-types-appendix.html">Unsupported Attachment Types</a>.</p> </li> <li> <p>If any of the MIME parts in a message contain content that is outside of the 7-bit ASCII character range, we recommend encoding that content.</p> </li> <li> <p>Per <a href="https://tools.ietf.org/html/rfc5321#section-4.5.3.1.6">RFC 5321</a>, the maximum length of each line of text, including the &lt;CRLF&gt;, must not exceed 1,000 characters.</p> </li> <li> <p>The message must contain all the required header fields. Check the returned error message for more information.</p> </li> <li> <p>The value of immutable headers must remain unchanged. Check the returned error message for more information.</p> </li> <li> <p>Certain unique headers can only appear once. Check the returned error message for more information.</p> </li> </ul>',
    )


class RawMessageContent(BaseModel):
    s3Reference: S3Reference


class PutRawMessageContentRequest(BaseModel):
    content: RawMessageContent
